FROM multiarch/qemu-user-static:x86_64-aarch64 as qemu

FROM arm64v8/node
COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin

WORKDIR /app

COPY . /app

EXPOSE 3000

RUN npm install

CMD node index.js
