apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-deployment
  labels:
    app: k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
      - name: k8s-api
        image: argeualcantara/k8s-api-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api
spec:
  type: NodePort
  selector:
    app: k8s-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31500
